[phases.setup]
providers = ["go", "node"]
packageManager = "pnpm@latest"

[phases.install]
cmds = [
  "corepack enable",
  "corepack prepare pnpm@latest --activate",
  "pnpm install --frozen-lockfile",
  "cd backend && go mod download"
]

[phases.build]
cmds = [
  "pnpm build"
]

[start]
cmd = "./start.sh"

[variables]
NODE_ENV = "production"
GO111MODULE = "on"
GOTOOLCHAIN = "local"
NODE_OPTIONS = "--max-old-space-size=4096"
