services:
  # Frontend service (Astro+Svelte with Node.js SSR)
  frontend:
    image: ogdrip-frontend:test
    ports:
      - '3000:3000'
    environment:
      - BACKEND_URL=http://backend:8888
      - PUBLIC_BACKEND_URL=http://localhost:8888
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3000
    depends_on:
      - backend
    restart: unless-stopped
    volumes:
      - outputs:/app/outputs

  # Backend service (Go with ChromeDP)
  backend:
    image: ogdrip-backend:test
    ports:
      - '8888:8888'
    environment:
      - PORT=8888
      - BASE_URL=http://localhost:8888
      - ENABLE_CORS=true
      - CHROME_FLAGS=--no-sandbox,--disable-dev-shm-usage,--disable-gpu,--headless,--disable-software-rasterizer
      - OUTPUT_DIR=/app/outputs
    volumes:
      - outputs:/app/outputs
    restart: unless-stopped

volumes:
  outputs:
