services:
  # Frontend service (Astro+Svelte with Node.js SSR)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.production
    ports:
      - '3000:3000'
    environment:
      - BACKEND_URL=https://api.og-drip.com
      - PUBLIC_BACKEND_URL=https://api.og-drip.com
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3000
      - ASTRO_TELEMETRY_DISABLED=1
      - COOLIFY_URL=https://og-drip.com,https://www.og-drip.com
      - COOLIFY_FQDN=og-drip.com,www.og-drip.com
    depends_on:
      - backend
    restart: unless-stopped
    volumes:
      - outputs:/app/outputs
      - ./frontend/public/images:/app/images
    labels:
      caddy: og-drip.com, www.og-drip.com
      caddy.reverse_proxy: 'localhost:3000'
      # Additional helpful Caddy configs
      caddy.tls: 'internal'
      caddy.tls.protocols: 'tls1.2 tls1.3'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Backend service (Go with ChromeDP)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.production
    ports:
      - '8888:8888'
    environment:
      - PORT=8888
      - BASE_URL=https://api.og-drip.com
      - ENABLE_CORS=true
      - CORS_ORIGINS=https://og-drip.com,https://www.og-drip.com
      - OUTPUT_DIR=/app/outputs
      - ADMIN_TOKEN=${ADMIN_TOKEN:-admin}
      - COOLIFY_URL=https://api.og-drip.com
      - COOLIFY_FQDN=api.og-drip.com
      - SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
      - SSL_CERT_DIR=/etc/ssl/certs
      - CHROME_FLAGS=--no-sandbox,--disable-dev-shm-usage,--disable-gpu,--headless,--disable-software-rasterizer
    volumes:
      - outputs:/app/outputs
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 3G
          cpus: '2'
    labels:
      caddy: api.og-drip.com
      caddy.reverse_proxy: 'localhost:8888'
      # Additional helpful Caddy configs
      caddy.tls: 'internal'
      caddy.tls.protocols: 'tls1.2 tls1.3'
      # Add CORS headers directly in Caddy
      caddy.headers:
        "Access-Control-Allow-Origin * Access-Control-Allow-Methods 'GET, POST, OPTIONS, PUT,
        DELETE' Access-Control-Allow-Headers 'Content-Type, Accept, Authorization, X-Requested-With'"
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8888/api/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  outputs:
