services:
  # Frontend service (Astro+Svelte with Node.js + PNPM)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=https://www.og-drip.com
      - PUBLIC_BACKEND_URL=https://www.og-drip.com
      - NODE_ENV=production
      - SVELTE_FORCE_COMPILE=true
      - ASTRO_TELEMETRY_DISABLED=1
    depends_on:
      - backend
    restart: unless-stopped
    volumes:
      - outputs:/app/public/outputs
      - ./frontend/public/images:/app/public/images

  # Backend service (Go with ChromeDP)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    environment:
      - PORT=8888
      - BASE_URL=https://www.og-drip.com
      - ENABLE_CORS=true
      - OUTPUT_DIR=/app/outputs
    volumes:
      - outputs:/app/outputs
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G

volumes:
  outputs:
