services:
  # Frontend service (Astro+Svelte with Node.js SSR)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.production
    ports:
      - '3000:3000'
    environment:
      - BACKEND_URL=https://api.og-drip.com
      - PUBLIC_BACKEND_URL=https://api.og-drip.com
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3000
      - ASTRO_TELEMETRY_DISABLED=1
      - COOLIFY_URL=https://og-drip.com,https://www.og-drip.com
      - COOLIFY_FQDN=og-drip.com,www.og-drip.com
    depends_on:
      - backend
    restart: unless-stopped
    volumes:
      - outputs:/app/outputs
      - ./frontend/public/images:/app/images

  # Backend service (Go with ChromeDP)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.production
    ports:
      - '8888:8888'
    environment:
      - PORT=8888
      - BASE_URL=https://api.og-drip.com
      - ENABLE_CORS=true
      - CORS_ORIGINS=https://og-drip.com,https://www.og-drip.com
      - OUTPUT_DIR=/app/outputs
      - ADMIN_TOKEN=${ADMIN_TOKEN:-admin}
      - COOLIFY_URL=https://api.og-drip.com
      - COOLIFY_FQDN=api.og-drip.com
      - SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
      - SSL_CERT_DIR=/etc/ssl/certs
      - CHROME_FLAGS=--no-sandbox,--disable-dev-shm-usage,--disable-gpu,--headless,--disable-software-rasterizer
    volumes:
      - outputs:/app/outputs
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 3G
          cpus: '2'

volumes:
  outputs:
