services:
  # Frontend service - use pre-built image with SSR
  frontend:
    image: ogdrip-frontend:prebuilt
    ports:
      - '3000:3000'
    restart: unless-stopped

  # Backend service - build from production Dockerfile
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.production
    environment:
      - PORT=8888
      - BASE_URL=http://backend:8888
      - ENABLE_CORS=true
      - OUTPUT_DIR=/app/outputs
      - CHROME_PATH=/usr/bin/chromium
    volumes:
      - outputs:/app/outputs
    restart: unless-stopped

  # Nginx service for testing configuration
  nginx:
    image: nginx:latest
    ports:
      - '80:80' # Map to standard HTTP port for testing
      - '443:443' # Map to standard HTTPS port for testing
    volumes:
      - ./nginx.test.conf:/etc/nginx/conf.d/default.conf
      - outputs:/app/outputs
    depends_on:
      - frontend
      - backend
    # Command to create self-signed SSL certificates for local testing
    command:
      /bin/bash -c "mkdir -p /etc/letsencrypt/live/og-drip.com && openssl req -x509 -nodes -days 365
      -newkey rsa:2048 -keyout /etc/letsencrypt/live/og-drip.com/privkey.pem -out
      /etc/letsencrypt/live/og-drip.com/fullchain.pem -subj '/CN=og-drip.com' && nginx -g 'daemon
      off;'"

volumes:
  outputs:
