version: '3.8'

services:
  ogdrip:
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - "8888:8888"
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - BASE_URL=http://localhost:8888
      - CHROME_PATH=/usr/bin/chromium
      - GO111MODULE=on
      - GOTOOLCHAIN=local
      - NODE_OPTIONS=--max-old-space-size=4096
    volumes:
      - ./data:/app/data
      - ./outputs:/app/outputs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8888/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s