services:
  # Frontend service (Astro+Svelte static site with Node.js serve)
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.production
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=https://www.og-drip.com
      - PUBLIC_BACKEND_URL=https://www.og-drip.com
      - NODE_ENV=production
      - ASTRO_TELEMETRY_DISABLED=1
    depends_on:
      - backend
    restart: unless-stopped
    volumes:
      - outputs:/app/dist/outputs
      - ./frontend/public/images:/app/dist/images

  # Backend service (Go with ChromeDP)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.production
    ports:
      - "8888:8888"
    environment:
      - PORT=8888
      - BASE_URL=https://www.og-drip.com
      - ENABLE_CORS=true
      - OUTPUT_DIR=/app/outputs
      - ADMIN_TOKEN=${ADMIN_TOKEN:-admin}
    volumes:
      - outputs:/app/outputs
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G

volumes:
  outputs:
