[phases.setup]
nixPkgs = [
  "nodejs_22", 
  "go_1_22",
  "chromium",
  "font-manager",
  "fontconfig",
  "freetype",
  "liberation_ttf",
  "dejavu_fonts",
  "git"
]
cmds = [
  "git submodule sync --recursive",
  "git submodule update --init --recursive --force",
  "corepack enable",
  "corepack prepare pnpm@latest --activate"
]

[phases.install]
cmds = [
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = [
  "pnpm build",
  "cd backend && mkdir -p build && go build -o build/ogdrip-backend *.go",
  "chmod +x backend/build/ogdrip-backend"
]

[start]
cmd = "./start.sh"

[variables]
NODE_ENV = "production"
GO111MODULE = "on"
GOTOOLCHAIN = "local"
NODE_OPTIONS = "--max-old-space-size=4096"
PNPM_HOME = "/root/.local/share/pnpm"
PATH = "/root/.local/share/pnpm:${PATH}"
CHROME_PATH = "/nix/store/*-chromium-*/bin/chromium"
DISPLAY = ":99"
FONTCONFIG_PATH = "/etc/fonts"
