[phases.setup]
nixPkgs = ["go", "nodejs", "pnpm", "chromium"]

[phases.install]
cmds = [
  "pnpm install --recursive --shamefully-hoist"
]

[phases.build]
cmds = ["pnpm build"]

[start]
cmd = "./start.sh"
