[phases.setup]
nixPkgs = ["nodejs_22", "go_1_22"]
cmds = [
  "corepack enable",
  "corepack prepare pnpm@latest --activate"
]

[phases.install]
cmds = [
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = [
  "pnpm build",
  "cd backend && go build -o build/ogdrip-backend *.go"
]

[start]
cmd = "./start.sh"

[variables]
NODE_ENV = "production"
GO111MODULE = "on"
GOTOOLCHAIN = "local"
NODE_OPTIONS = "--max-old-space-size=4096"
PNPM_HOME = "/root/.local/share/pnpm"
PATH = "/root/.local/share/pnpm:${PATH}"
