[phases.setup]
nixPkgs = ["go", "nodejs", "pnpm", "chromium"]

[phases.install]
cmds = ["pnpm install"]

[phases.build]
cmds = ["pnpm build"]

[start]
cmd = "./start.sh"

[variables]
CHROME_PATH = "/nix/store/chromium/bin/chromium"
