version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - '8888:8888'
    environment:
      - PORT=8888
      - BASE_URL=http://localhost:8888
      - CHROME_PATH=/usr/bin/chromium
      - OUTPUT_DIR=/app/outputs
      - ENABLE_CORS=true
    volumes:
      - ./outputs:/app/outputs
    command: ['./ogdrip-backend', '-service']
