services:
  ogdrip:
    image: ${COOLIFY_IMAGE_NAME}
    ports:
      - '3000:3000' # Frontend port
      - '8888:8888' # Backend API port
    volumes:
      - ogdrip_data:/app/outputs
    environment:
      # These will be overridden by Coolify's environment variables
      - PUBLIC_BACKEND_URL=${PUBLIC_BACKEND_URL:-http://localhost:8888}
      - BACKEND_URL=${BACKEND_URL:-http://localhost:8888}
      - ADMIN_TOKEN=${ADMIN_TOKEN:-admin}
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8888/api/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  ogdrip_data:
