#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running pre-commit hook..."
echo "Building frontend with pnpm build..."

# Navigate to the frontend directory from the git root
cd "$(git rev-parse --show-toplevel)/frontend" && pnpm build
