name: Build and Push Ubuntu-based Docker Image

on:
  push:
    branches: [main]
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      # Set up Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      # Set up Node.js and pnpm
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install pnpm
        run: npm install -g pnpm

      # Install dependencies for Go CGO
      - name: Install CGO dependencies
        run: sudo apt-get update && sudo apt-get install -y gcc libc6-dev pkg-config libsqlite3-dev

      # Build frontend
      - name: Build frontend
        run: |
          cd frontend
          pnpm install
          pnpm build

      # Build backend
      - name: Build backend
        run: |
          cd backend
          go mod download
          CGO_ENABLED=1 go build -v -o ogdrip-backend .

      - name: Convert repository owner to lowercase
        id: repo-owner-lowercase
        run:
          echo "owner=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >>
          $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push combined image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker-build/Dockerfile.combined
          push: true
          tags: ghcr.io/${{ steps.repo-owner-lowercase.outputs.owner }}/ogdrip:latest
